### PR TITLE
Add drag and drop functionality to fluent contents.

### LINKED ISSUE #50: Drag and Drop
Hello, I am working with mezzanine and they have a nice drag and drop interface for models that require it, in their admin. It would be nice if a similar drag and drop feature applicable to ContentItems in a Placeholder.

### PR DESCRIPTION
**Pull request by sjdines**
Closes #50 (https://github.com/edoburu/django-fluent-
contents/issues/50).

This will add a new requirement for jQuery UI into the project.

### CODE REVIEW

**Comment by vdboor** [comment]
Wow, thanks a lot for working on this!
It looks pretty good so far!

The only thing it would have to do, is support the wysiwyg editor. The active TinyMCE editor breaks when you drag&drop it. (using django-tinymce 2.0.5). The regular up/down arrows fix this by calling `disable_pageitem()` / `enable_pageitem()` in `cp_plugins._move_item_to`. Would it be possible to incorporate that somehow?

**Comment by sjdines** [comment]
@vdboor thanks for the feedback; I was unaware of that issue. It should be resolved with the latest patch.

**Comment by cybersimon** [comment]
@sjdines I'd love to see this get merged in. What do we need to do to fix the failing tests?

**Comment by sjdines** [comment]
@cybersimon I believe they were unrelated failures to this ticket. I will merge in master to the branch and push again when I get a chance

**Comment by sjdines** [comment]
@cybersimon as expected unrelated test failures.

@vdboor please let me know if you have any further questions / feedback

**Comment by vdboor** [comment]
@sjdines I've been testing this feature, and one thing still broke. When I switch layouts on the page, the events no longer bind. I think this is best solved by integrating `sortable.js` into the `cp_plugins.js` logic (in `move_items_to_pane()`). Right now all events are handled with delegation through `$.fn.on()` since the content items could be recreated, etc..

**Comment by vdboor** [comment]
@sjdines : I've merged this feature in v1.1.7 (and just released 1.1.8). I've taken a slightly different approach (see 54a602fe629e3a175f0c2ce997e47890d3fb6f3b), but this pull request was the inspiration to get it working! Thanks for your work, it has been really helpful to get this implemented  :-)

**Comment by sjdines** [comment]
@vdboor thanks for letting me know the feature is there and for implementing it!

**Pull request closed without merging**
